name: "milvus"
description: "setup milvus"

runs:
    using: "composite"
    steps:
      - name: Download Milvus Installation Script
        shell: bash
        run: |
          # Download the Milvus standalone embed script
          curl -sfL https://raw.githubusercontent.com/milvus-io/milvus/master/scripts/standalone_embed.sh -o standalone_embed.sh
          # Make the script executable
          chmod +x standalone_embed.sh
