name: "milvus"
description: "setup milvus"

runs:
    using: "composite"
    steps:
      - name: Download Milvus Installation Script
        shell: bash
        working-directory: ${{ github.action_path }}
        run: |
          # Download the Milvus standalone embed script
          curl -sfL https://raw.githubusercontent.com/milvus-io/milvus/master/scripts/standalone_embed.sh -o ${{ github.action_path }}/standalone_embed.sh
          # Make the script executable
          chmod +x ${{ github.action_path }}/standalone_embed.sh
          echo "${{ github.action_path }}"
          pwd
          ls -l
