name: "db-runner"
description: "db runner"
inputs:
    DB-name:
        description: "DB name"
        required: false
        default: "VectorDB"

runs:
    using: "composite" # Mandatory parameter
    steps:
        - id: project
          uses: ./.github/actions/project

        - if: inputs.DB-name=='VectorDB'
          name: Run Milvus DB
          uses: ./.github/actions/service/vectordb
          with:
              stop: false
              clean: false
              start: true
              ports: 19530 19531 19532