name: Pull Request Workflow

on:
  pull_request:
    branches: [ master ]  # 仅当 Pull Request 目标分支是 main 时触发

jobs:
  Run_Milvus:
    strategy:
      fail-fast: false
      matrix:
#        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}

    outputs:
      db_host: ${{ steps.db_info.outputs.host }}
      db_port: ${{ steps.db_info.outputs.port }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 检出代码

      - name: Run DB
        uses: ./.github/actions/dbRunner
        with:
          DB-name: "VectorDB"

      - id: db_info
        run: |
          echo "::set-output name=host::$(hostname -I | awk '{print $1}')"
          echo "::set-output name=port::19530"
          echo "::set-output name=port1::19531"
          echo "::set-output name=port2::19532"


  Java-Test:
    needs: Run_Milvus
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - if : runner.os == 'macOS'
        name: Environment dependence
        uses: ./.github/actions/dependence
        with:
          java: "11"

      - if : runner.os != 'macOS'
        name: Environment dependence
        uses: ./.github/actions/dependence
        with:
          java: "8"

      - name: show env
        shell: bash
        run: |
          java -version
          echo ${{ needs.Run_Milvus.outputs.host }}
          echo ${{ needs.Run_Milvus.outputs.port }}
          echo ${{ needs.Run_Milvus.outputs.port1 }}
          echo ${{ needs.Run_Milvus.outputs.port2 }}

#      - if: runner.os == 'Windows'
#        name: Verify Docker installation on Windows
#        shell: pwsh
#        run: |
#          $env:Path += ";${{ github.workspace }}"
#          docker --version
#          docker-compose --version
#
#      - if: runner.os != 'Windows'
#        name: Verify Docker installation
#        shell: bash
#        run: |
#          docker --version
#          docker-compose --version
#
#      - name: Run Milvus DB
#        uses: ./.github/workflows/actions/service/milvus
#        with:
#          stop: false
#          clean: false
#          start: true
#          ports: 19530 19531 19532
#
#
#      - name: Run tests
#        shell: bash
#        run: |
#          docker ps -a
#          if ss -tuln | grep -q ":19530 "; then
#            echo "Port 19530 is open."
#          else
#            echo "Port 19530 is not open."
#          fi
#          mvn test  # 运行测试

