name: Pull Request Workflow

on:
  pull_request:
    branches: [ master ]  # 仅当 Pull Request 目标分支是 main 时触发

jobs:
  Run_Milvus:
    strategy:
      fail-fast: false
      matrix:
#        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        os: ["windows-latest"]
    runs-on: ${{ matrix.os }}

    outputs:
      host: ${{ steps.db_info.outputs.host }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 检出代码

      - if : runner.os == 'macOS'
        name: Environment dependence
        uses: ./.github/actions/dependence
        with:
          java: "11"

      - if : runner.os != 'macOS'
        name: Environment dependence
        uses: ./.github/actions/dependence
        with:
          java: "8"

#      - name: Run DB
#        uses: ./.github/actions/dbRunner
#        with:
#          DB-name: "VectorDB"
      - name: pwd
        shell: bash
        run: |
          pwd

      - uses: vedantmgoyal9/setup-wsl2@main
      - run: apt update && apt upgrade -y
        shell: wsl-run {0}

      - run: |
          pwd
          ls -al
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
        shell: wsl-run {0}


      - name: Network test
        shell: bash
        run: |
          docker ps
               
          for port in 19530 19531 19532; do
            if netstat -an | grep -q ".*:$port.*LISTEN"; then
              echo "Port $port is open."
            else
              echo "Port $port is not open."
            fi
          done
          
          docker ps -a

