name: Pull Request Workflow

on:
  pull_request:
    branches: [ master ]  # 仅当 Pull Request 目标分支是 main 时触发

jobs:
  build-and-test:
#    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行器
    runs-on: macos-latest  # 使用最新的 Ubuntu 运行器
#    runs-on: windows-latest  # 使用最新的 Ubuntu 运行器

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 检出代码

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'  # Specify the JDK version (e.g., 8, 11, 17)
          cache: "maven"
#          distribution: "temurin"
          distribution: ${{ runner.os == 'macOS' && 'liberica' || 'temurin' }}

      - if: runner.os == 'macOS'
        name: Install Docker on MacOS
        shell: bash
        run: |
          brew update
          brew install docker
          brew install colima
          LIMACTL_PATH=$(brew --prefix)/bin/limactl
          sudo curl -L -o $LIMACTL_PATH https://github.com/mikekazakov/lima-nohvf/raw/master/limactl && sudo chmod +x $LIMACTL_PATH
          colima start --network-address --arch arm64 --vm-type=qemu
          docker --version

      - name: Verify Docker Compose installation
        run: docker --version

      - name: Run tests
        run: mvn test  # 运行测试

